apiVersion: v1
kind: Service
metadata:
  name: "spring-app-svc"
  labels:
    app: "spring-app-svc"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8222
      protocol: TCP
      name: http
  selector:
    app: "spring-app"
